export const FETCH_BEERS_REQUEST = "FETCH_BEERS_REQUEST";
export const FETCH_BEERS_SUCCESS = "FETCH_BEERS_SUCCESS";
export const FETCH_BEERS_FAILURE = "FETCH_BEERS_FAILURE";

export const CHANGE_MIN_ML = "CHANGE_MIN_ML";
export const CHANGE_MAX_ML = "CHANGE_MAX_ML";
export const CHANGE_MIN_PRICE = "CHANGE_MIN_PRICE";
export const CHANGE_MAX_PRICE = "CHANGE_MAX_PRICE";
